FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/servidor ./cmd/servidor

FROM alpine:3.20
COPY --from=build /bin/servidor /bin/servidor
EXPOSE 9000
ENTRYPOINT ["/bin/servidor"]
